export { default as isString } from './utils/is-string'
export { default as isNumber } from './utils/is-number'
export { default as isBoolean } from './utils/is-boolean'
export { default as isFunction } from './utils/is-function'
export { default as isAsyncFunction } from './utils/is-async-function'
export { default as isPromise } from './utils/is-promise'
export { default as isObject } from './utils/is-object'
export { default as isNull } from './utils/is-null'
